package main_test

import (
	"encoding/json"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/kyleking/aragonite/ghcassette"

	"github.com/kyleking/second-look/internal/conversations"
)

// The conversation queue is one GraphQL call and nothing local, so these run
// outside a checkout, and the read marks they would write are pointed at a
// temporary config directory rather than the real one.
//
// The cassette is built here rather than checked in. A real recording carries
// the private repository names, logins, and pull request titles of whatever is
// open, and this repository is public; building it from conversations.Args means
// the call it answers is the call the fetcher makes, which a hand-written copy
// of a 60-line GraphQL query would stop being on the first edit.
func TestThreads(t *testing.T) {
	t.Parallel()

	s := ghcassette.Replay(t, queueCassette(t))

	res := runCLI(t, s, t.TempDir(), "threads")
	if res.code != 0 {
		t.Fatalf("threads failed: %s%s", res.stdout, res.stderr)
	}

	for _, want := range []string{
		conversations.BucketNew,
		conversations.BucketWaiting,
		conversations.BucketAwaiting,
		// The bot's inline thread is admitted, since it is anchored to code and
		// can be resolved.
		"a.go:12",
		// The pull request title rides along, because a repository and a number
		// are not enough to know what a conversation is about.
		"mine",
	} {
		if !strings.Contains(res.stdout, want) {
			t.Errorf("%q is missing from the queue:\n%s", want, res.stdout)
		}
	}

	// A bot's pull request comment, a review body it wrote, and a comment
	// already thumbs-upped are all dropped, and the queue is worthless if they
	// are not.
	for _, unwanted := range []string{"Coverage report", "generated by a bot", "already handled"} {
		if strings.Contains(res.stdout, unwanted) {
			t.Errorf("%q reached the queue:\n%s", unwanted, res.stdout)
		}
	}

	s.RequireAllPlayed(t)
}

// Printing the queue is not reading it, so a run that emptied the first bucket
// by being run would hide the one thing that bucket is for.
func TestThreadsWritesNoReadMarks(t *testing.T) {
	t.Parallel()

	s := ghcassette.Replay(t, queueCassette(t))
	home := quietHome(t)

	res := runCLIEnv(t, s, t.TempDir(), []string{"HOME=" + home, "XDG_CONFIG_HOME=" + home + "/.config"}, "threads")
	if res.code != 0 {
		t.Fatalf("threads failed: %s%s", res.stdout, res.stderr)
	}

	if found := marks(t, home); found != "" {
		t.Errorf("printing the queue wrote read marks at %s", found)
	}
}

// marks is where read state was written under home, or empty when none was.
func marks(t *testing.T, home string) string {
	t.Helper()

	var found string

	err := filepath.WalkDir(home, func(path string, d fs.DirEntry, err error) error {
		if err == nil && !d.IsDir() && d.Name() == "conversations.toml" {
			found = path
		}

		return nil
	})
	if err != nil {
		t.Fatalf("walking %s: %v", home, err)
	}

	return found
}

// --json is what an agent reads, so the buckets and every field a script needs
// have to survive it.
func TestThreadsJSON(t *testing.T) {
	t.Parallel()

	s := ghcassette.Replay(t, queueCassette(t))

	res := runCLI(t, s, t.TempDir(), "threads", "--json")
	if res.code != 0 {
		t.Fatalf("threads --json failed: %s%s", res.stdout, res.stderr)
	}

	var buckets []struct {
		Name  string                       `json:"name"`
		Items []conversations.Conversation `json:"items"`
	}

	if err := json.Unmarshal([]byte(res.stdout), &buckets); err != nil {
		t.Fatalf("reading the buckets: %v\n%s", err, res.stdout)
	}

	if len(buckets) != 3 {
		t.Fatalf("printed %d buckets, want 3:\n%s", len(buckets), res.stdout)
	}

	var seen int

	for i := range buckets {
		for j := range buckets[i].Items {
			c := &buckets[i].Items[j]
			seen++

			if c.Repository == "" || c.Number == 0 || len(c.Notes) == 0 || !c.Why.Any() {
				t.Errorf("a conversation carries too little to act on: %+v", c)
			}
		}
	}

	if seen == 0 {
		t.Fatal("no conversations were printed, so nothing here is exercised")
	}
}

// queueCassette answers the one call a fetch makes with the hand-written queue
// the conversations package tests against, which is the only fixture of this
// shape and the one place its rules are written down.
func queueCassette(t *testing.T) string {
	t.Helper()

	body, err := os.ReadFile(filepath.Join("..", "..", "internal", "conversations", "testdata", "queue.json"))
	if err != nil {
		t.Fatalf("reading the queue fixture: %v", err)
	}

	c := &ghcassette.Cassette{Interactions: []ghcassette.Interaction{{
		Args:   conversations.Args(conversations.DefaultLimit),
		Stdout: string(body),
	}}}

	path := filepath.Join(t.TempDir(), "threads.golden")
	if err := ghcassette.Save(path, c); err != nil {
		t.Fatalf("writing the queue cassette: %v", err)
	}

	return path
}

// The queue screen renders only on a terminal, so this drives the built binary
// through a pty: the buckets are drawn, a row expands where it sits, and what
// was read is written to disk on the way out rather than on every keystroke.
func TestThreadsScreen(t *testing.T) {
	t.Parallel()

	s := ghcassette.Replay(t, queueCassette(t))
	home := quietHome(t)

	// Both, because os.UserConfigDir reads XDG_CONFIG_HOME on Linux and ignores
	// it on macOS: setting only HOME leaves the marks under the harness's own
	// config directory there, where nothing looking under home finds them.
	sc := openReview(t, s, t.TempDir(), "HOME="+home, "XDG_CONFIG_HOME="+home+"/.config", "threads")
	sc.await("second-look conversations")
	sc.await(conversations.BucketNew)
	sc.await("a.go:12")

	// enter opens the conversation in place and marks it read, and the row stays
	// where it is: recomputing the bucket after a mark used to move it out from
	// under the cursor.
	sc.press("\r")
	sc.await("read ")

	sc.press("q")

	if code := sc.wait(); code != 0 {
		t.Fatalf("the queue exited %d:\n%s", code, sc.text())
	}

	path := marks(t, home)
	if path == "" {
		t.Fatalf("nothing was written, so the read mark did not survive the screen:\n%s", sc.text())
	}

	raw, err := os.ReadFile(path) // #nosec G304 -- a path this test's own HOME holds
	if err != nil {
		t.Fatal(err)
	}

	// One keypress marks one conversation, and what was written is the row the
	// screen said it read rather than whatever happened to be first.
	if got := strings.Count(string(raw), "[[conversation]]"); got != 1 {
		t.Errorf("wrote %d marks for one keypress:\n%s", got, raw)
	}

	read := readLine.FindStringSubmatch(sc.text())
	if read == nil {
		t.Fatalf("the screen never said what it read:\n%s", sc.text())
	}

	for _, want := range strings.Fields(read[1]) {
		if !strings.Contains(string(raw), want) {
			t.Errorf("it read %q and wrote:\n%s", read[1], raw)
		}
	}
}

// readLine is what the footer says after a conversation is read: the pull
// request and the anchor, which is what the mark on disk has to name.
var readLine = regexp.MustCompile(`read (\S+#\d+ \S+)`)
